data:
  raw_path: "data/raw/data.csv"
  processed_path: "data/processed/train.csv"

model:
  type: "DecisionTreeClassifier"
  params:
    max_depth: 5
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 42

training:
  test_size: 0.2
  target_column: "label"