data:
  raw_path: "data/raw/data.csv"
  processed_path: "data/processed/train.csv"

model:
  type: "RandomForestClassifier"
  params:
    n_estimators: 100
    max_depth: 5
    random_state: 42

training:
  test_size: 0.2
  target_column: "label"
