data:
  raw_path: "data/raw/data.csv"
  processed_path: "data/processed/train.csv"

model:
  type: "GradientBoostingClassifier"
  params:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 3
    random_state: 42

training:
  test_size: 0.2
  target_column: "label"