data:
  raw_path: "data/raw/data.csv"
  processed_path: "data/processed/train.csv"

model:
  type: "LogisticRegression"
  params:
    C: 1.0
    max_iter: 1000
    random_state: 42

training:
  test_size: 0.2
  target_column: "label"