data:
  raw_path: "data/raw/data.csv"
  processed_path: "data/processed/train.csv"

model:
  type: "SVC"
  params:
    C: 1.0
    kernel: "rbf"
    gamma: "scale"
    random_state: 42

training:
  test_size: 0.2
  target_column: "label"